export {default as AboutPage} from '../Screens/AboutPage'
export {default as AppointmentPage} from '../Screens/AppointmentPage'
export {default as CartPage} from '../Screens/CartPage'
export {default as ShopPage} from '../Screens/ShopPage'
export {default as WelcomePage} from '../Screens/WelcomePage'
export {default as ProductPage} from '../Componets/ShopScreen/ProductPage'
export {default as CheckOutPage} from '../Screens/CheckOutPage'
export {default as PaymentInfoPage} from '../Componets/CheckOut/PaymentInfoPage'